"""sale_items combo_id nullable producto_id

Revision ID: eac6e307cc1c
Revises: 7876cf188323
Create Date: 2026-06-10 18:46:40.295194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac6e307cc1c'
down_revision = '7876cf188323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combo_id', sa.Integer(), nullable=True))
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_sale_items_combo_id', 'combos', ['combo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_items_combo_id', type_='foreignkey')
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('combo_id')

    # ### end Alembic commands ###
